DesignAirDemo/DesignAirDemo/Models/Entities/Project.cs
namespace DesignAirDemo.Models.Entities
{
    public class Project
    {
        public Project()
        {
            Contractors = new List<Contractor>();
            Suppliers = new List<Supplier>();
            Operations = new List<Operation>(); 
        }


        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string Name { get; set; } = string.Empty;

        public decimal TotalDebitBalance { get; set; }

        public decimal TotalCreditBalance { get; set; }

        public string ClientId { get; set; } = string.Empty;

        public virtual Client Client { get; set; }

        public virtual List<Contractor> Contractors { get; set; }

        public virtual List<Supplier> Suppliers { get; set; }

        public virtual List<Operation> Operations { get; set; } 
    }
}

DesignAirDemo/DesignAirDemo/Controllers/OperationsController.cs
using DesignAirDemo.Data;
using DesignAirDemo.Models;
using DesignAirDemo.Models.DTOModels;
using DesignAirDemo.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Contracts;

namespace DesignAirDemo.Controllers
{
    public class OperationsController : Controller
    {
        private readonly AppDbContext _db;
        private readonly string _tempPath;

        public OperationsController(AppDbContext db)
        {
            _db = db;
            _tempPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images");
        }

        [HttpGet()]
        public async Task<IActionResult> GetOperations([FromQuery] AskForOperations model)
        {
            var project = await _db.Projects.Include(p => p.Operations).SingleOrDefaultAsync(p => p.Id == model.ProjectId);
            if(project == null) 
                return NotFound();

            if(model.Type == "Contractors")
            {
                var contractor = await _db.Contractors.FindAsync(model.UserId);
                if (contractor == null)
                    return NotFound();
               
                var getOperationsDto = project.Operations.Where(o => o.ContractorId == model.UserId).Select(op => new GetOperationDto
                {
                    Id = op.Id,
                    Description = op.Description,
                    Type = op.Type,
                    Amount = op.Amount,
                    Sign = op.Sign,
                    DateTime = op.Date,
                    FilePath = op.FilePath
                }).ToList();

                var operationsDto = new GetOperationsDto
                {
                    UserId = model.UserId,
                    ProjectId = project.Id,
                    Type = model.Type,
                    UserName = contractor.Name,
                    ProjectName = project.Name,
                    TotalCreditBalance = getOperationsDto.Where(op => op.Sign).Sum(op => op.Amount),
                    TotalDebitBalance = getOperationsDto.Where(op => !op.Sign).Sum(op => op.Amount) ,
                    getOperationDto = getOperationsDto,
                };
                operationsDto.Different = operationsDto.TotalCreditBalance - operationsDto.TotalDebitBalance;
                return View(operationsDto);
            }
            else if(model.Type == "Suppliers")
            {
                var supplier = await _db.Suppliers.FindAsync(model.UserId);
                if (supplier == null)
                    return NotFound();

                var getOperationsDto = project.Operations.Where(o => o.SupplierId == model.UserId).Select(op => new GetOperationDto
                {
                    Id = op.Id,
                    Description = op.Description,
                    Type = op.Type,
                    Amount = op.Amount,
                    Sign = op.Sign,
                    DateTime = op.Date,
                    FilePath = op.FilePath
                }).ToList();

                var operationsDto = new GetOperationsDto
                {
                    UserId = model.UserId,
                    ProjectId = project.Id,
                    Type = model.Type,
                    UserName = supplier.Name,
                    ProjectName = project.Name,
                    TotalCreditBalance = getOperationsDto.Where(op => op.Sign).Sum(op => op.Amount),
                    TotalDebitBalance = getOperationsDto.Where(op => !op.Sign).Sum(op => op.Amount),
                    getOperationDto = getOperationsDto
                };
                operationsDto.Different = operationsDto.TotalCreditBalance - operationsDto.TotalDebitBalance;
                return View(operationsDto);
            }
            else
            {
                var client = await _db.Clients.FindAsync(model.UserId);
                if (client == null)
                    return NotFound();

                var getOperationsDto = project.Operations.Where(o => o.ClientId == model.UserId).Select(op => new GetOperationDto
                {
                    Id = op.Id,
                    Description = op.Description,
                    Type = op.Type,
                    Amount = op.Amount,
                    Sign = op.Sign,
                    DateTime = op.Date,
                    FilePath = op.FilePath
                }).ToList();

                var operationsDto = new GetOperationsDto
                {
                    UserId = model.UserId,
                    ProjectId = project.Id,
                    Type = model.Type,
                    UserName = client.Name,
                    ProjectName = project.Name,
                    TotalCreditBalance = getOperationsDto.Where(op => op.Sign).Sum(op => op.Amount),
                    TotalDebitBalance = getOperationsDto.Where(op => !op.Sign).Sum(op => op.Amount),
                    getOperationDto = getOperationsDto
                };
                operationsDto.Different = operationsDto.TotalCreditBalance - operationsDto.TotalDebitBalance;
                return View(operationsDto);
            }
        }

        [HttpGet()]
        public async Task<IActionResult> AddOperation([FromQuery]AskForOperations model)
        {
            var project = await _db.Projects.FindAsync(model.ProjectId);
            if (project == null) return NotFound();

            if (model.Type == "Contractors")
            {
                var contractor = await _db.Contractors.FindAsync(model.UserId);
                if (contractor == null)
                    return NotFound();
            }
            else if (model.Type == "Suppliers")
            {
                var supplier = await _db.Suppliers.FindAsync(model.UserId);
                if (supplier == null)
                    return NotFound();
            }
            else
            {
                var client = await _db.Clients.FindAsync(model.UserId);
                if (client == null)
                    return NotFound();
            }

            var addOperationDto = new AddOperationDto
            {
                Id = model.UserId,
                Type = model.Type,
                ProjectId = model.ProjectId,
            };

            await createOperationTypesSelectList();
            return View(addOperationDto);
        }

        [HttpGet]
        public async Task<IActionResult> DownloadImage(string id)
        {
            var operation = await _db.Operations.FindAsync(id);
            if (operation == null) return NotFound();

            string fileName = operation.FilePath;

            if (string.IsNullOrEmpty(fileName))
            {
                return BadRequest("File name cannot be empty.");
            }

            var filePath = Path.Combine(_tempPath, fileName);
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound("File not found.");
            }

            var memory = new MemoryStream();
            using (var stream = new FileStream(filePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "application/octet-stream", operation.Description + Path.GetExtension(operation.FilePath));
        }

        [HttpPost()]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOperation(AddOperationDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var project = await _db.Projects.FindAsync(model.ProjectId);
            if (project == null)
                return NotFound();

            var operationType = await _db.OperationTypes.FindAsync(model.OperationTypeId);
            if (operationType == null)
                return NotFound();

            var operation = new Operation
            {
                Type = operationType.Name,
                Sign = operationType.Sign,
                Description = model.Description,
                Amount = model.Amount,
                ProjectId = model.ProjectId,
            };


            var filePath = Path.Combine(_tempPath, operation.Id + Path.GetExtension(model.Image.FileName));
            await using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await model.Image.CopyToAsync(stream);
            }

            operation.FilePath = filePath;

            if (model.Type == "Contractors")
            {
                var contractor = await _db.Contractors.FindAsync(model.Id);
                if (contractor == null)
                    return NotFound();
                operation.ContractorId = model.Id;
                if(operationType.Sign)
                    contractor.TotalCreditBalance += model.Amount;
                else
                    contractor.TotalDebitBalance += model.Amount;
            }
            else if (model.Type == "Suppliers")
            {
                var supplier = await _db.Suppliers.FindAsync(model.Id);
                if (supplier == null)
                    return NotFound();
                operation.SupplierId = model.Id;
                if (operationType.Sign)
                    supplier.TotalCreditBalance += model.Amount;
                else
                    supplier.TotalDebitBalance += model.Amount;
            }
            else
            {
                var client = await _db.Clients.FindAsync(model.Id);
                if (client == null)
                    return NotFound();
                operation.ClientId = model.Id;
                if (operationType.Sign)
                    client.TotalCreditBalance += model.Amount;
                else
                    client.TotalDebitBalance += model.Amount;
            }

            if (operationType.Sign)
            {

DesignAirDemo/DesignAirDemo/Controllers/ProjectsController.cs
using DesignAirDemo.Data;
using DesignAirDemo.Models.DTOModels;
using DesignAirDemo.Models.DTOModels.PojectDto;
using DesignAirDemo.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DesignAirDemo.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly AppDbContext _db;

        public ProjectsController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet()]
        public async Task<IActionResult> All()
        {
            var projects = await _db.Projects.ToListAsync();
            var projectsDto = projects.Select(p => new GetProjectDto
            {
                Id = p.Id,
                Name = p.Name,
                TotalDebitBalance = p.TotalDebitBalance,
                TotalCreditBalance = p.TotalCreditBalance,
                CurrentDebitBalance = Math.Max(0, p.TotalDebitBalance - p.TotalCreditBalance),
                CurrentCreditBalance = Math.Max(0, p.TotalCreditBalance - p.TotalDebitBalance),
                ClientId = p.ClientId
            }).ToList();

            return View(projectsDto);
        }

        [HttpGet()]
        public async Task<IActionResult> Search(string Name)
        {
            var projects = await _db.Projects.Where(p => p.Name.Contains(Name)).ToListAsync();
            var projectsDto = projects.Select(p => new GetProjectDto
            {
                Id = p.Id,
                Name = p.Name,
                TotalDebitBalance = p.TotalDebitBalance,
                TotalCreditBalance = p.TotalCreditBalance,
                CurrentDebitBalance = Math.Max(0, p.TotalDebitBalance - p.TotalCreditBalance),
                CurrentCreditBalance = Math.Max(0, p.TotalCreditBalance - p.TotalDebitBalance),
                ClientId = p.ClientId
            }).ToList();

            return PartialView("_SearchProjects" , projectsDto);
        }

        [HttpGet()]
        public async Task<IActionResult> Add()
        {
            await createClientSelectList();
            return View();
        }

        [HttpGet()]
        public async Task<IActionResult> AddToProject(string id, string type)
        {
            if (type == "Suppliers")
            {
                var supplier = await _db.Suppliers.FindAsync(id);
                if (supplier == null)
                    return NotFound();
            }
            else if (type == "Contractors")
            {
                var contractor = await _db.Contractors.FindAsync(id);
                if (contractor == null)
                    return NotFound();
            }

            var addToProjectDto = new AddToProjectDto
            {
                Id = id,
                Type = type,
            };
            await createAddToProjectSelectList(id, type);
            return View(addToProjectDto);
        }

        [HttpPost()]
        public async Task<IActionResult> Add(AddProjectDto modelDto)
        {
            if (!ModelState.IsValid)
                return View(ModelState);

            var project = new Project
            {
                Name = modelDto.Name,
                ClientId = modelDto.ClientId,
            };
            var dashboardData = await _db.DashboardData.FirstOrDefaultAsync();
            await _db.Projects.AddAsync(project);
            dashboardData.Projects += 1;
            await _db.SaveChangesAsync();

            return RedirectToAction("All");
        }

        [HttpPost()]
        public async Task<IActionResult> AddToProject(AddToProjectDto modelDto)
        {
            if(!ModelState.IsValid)
                return View(ModelState);

            var project = await _db.Projects.FindAsync(modelDto.ProjectId);
            if (project == null)
                return NotFound();

            if (modelDto.Type == "Suppliers")
            {
                var supplier = await _db.Suppliers.FindAsync(modelDto.Id);
                if (supplier == null)
                    return NotFound();
                supplier.Projects.Add(project);
            }
            else if (modelDto.Type == "Contractors")
            {
                var contractor = await _db.Contractors.FindAsync(modelDto.Id);
                if (contractor == null)
                    return NotFound();
                contractor.Projects.Add(project);
            }

            await _db.SaveChangesAsync();
            return View(modelDto);
        }

        private async Task createAddToProjectSelectList(string id, string type)
        {
            if (type == "Contractors")
            {
                var contractor = await _db.Contractors.Include(c => c.Projects).FirstOrDefaultAsync(c => c.Id == id);
                if (contractor == null)
                    return;
                var projects = _db.Projects.Where(p => !contractor.Projects.Contains(p));
                SelectList listItems = new SelectList(projects, "Id", "Name", 1);
                ViewBag.ProjectList = listItems;
            }
            else
            {
                var supplier = await _db.Suppliers.Include(c => c.Projects).FirstOrDefaultAsync(c => c.Id == id);
                if (supplier == null)
                    return;
                var projects = _db.Projects.Where(p => !supplier.Projects.Contains(p));
                SelectList listItems = new SelectList(projects, "Id", "Name", 1);
                ViewBag.ProjectList = listItems;
            }  
        }

        private async Task createClientSelectList(int? start = 1)
        {
            var clients = await _db.Clients.ToListAsync();
            SelectList listItems = new SelectList(clients, "Id", "Name", 1);
            ViewBag.ClientList = listItems;
        }
    }
}

DesignAirDemo/DesignAirDemo/Views/Projects/Add.cshtml
@model AddProjectDto

@{
    ViewData["Title"] = "New Project";
}

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add New Project</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="ClientId">Client</label>
            <select asp-for="ClientId" class="form-control" asp-items="@ViewBag.ClientList">
            </select>
            <span asp-validation-for="ClientId" class="text-danger"></span>
        </div>
        <br />
        <hr />
        <button typeof="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-action="All" asp-controller="Projects" class="btn btn-primary" style="width:150px">
            back to items
        </a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DesignAirDemo/DesignAirDemo/Views/Projects/AddToProject.cshtml
@model AddToProjectDto

@{
    ViewData["Title"] = "Add To Project";
}

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add To New Project</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>

        <div>
            <input class="from-control" asp-for="Id" hidden />
        </div>

        <div>
            <input class="from-control" asp-for="Type" hidden />
        </div>

        <div>
            <label asp-for="ProjectId">Project</label>
            <select asp-for="ProjectId" class="form-control" asp-items="@ViewBag.ProjectList"></select>
            <span asp-validation-for="ProjectId" class="text-danger"></span>
        </div>
        <br />
        <hr />
        <button typeof="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-action="All" asp-controller="@Model.Type" class="btn btn-primary" style="width:150px">
            back to items
        </a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DesignAirDemo/DesignAirDemo/Views/Projects/All.cshtml
@model List<GetProjectDto>

@{
    ViewData["Title"] = "Projects";
}


<div class="row pt-4" style="margin-bottom: 2%">
    <div class="col-6">
        <h2 class="text-primary">Projects View</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Projects" asp-action="Add" class="btn btn-primary">
            <i class="bi bi-plus"></i> &nbsp; Add New Project
        </a>
    </div>
</div>

<hr />

<div class="container mt-5">
    <div class="row">
        <div class="col-md-3">
            <input type="text" class="form-control" id="searchTerm" placeholder="Search for project..." />
        </div>
        <div class="col-md-2">
            <button id="searchButton" class="btn btn-primary w-100">Search</button>
        </div>
        <div class="col-md-2">
            <button id="clear" class="btn btn-secondary btn-danger w-100">Clear</button>
        </div>
    </div>
    <br />
    <div id="results" class="mt-3"></div>
    <br />
</div>

<hr />

<table class="table table-striped" id="tblProjects">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Current Debit Balance</th>
            <th scope="col">Current Credit Balance</th>
            <th scope="col">Total Debit Balance</th>
            <th scope="col">Total Credit Balance</th>
            <th scope="col">Client</th>
            <th scope="col">Contractors</th>
            <th scope="col">Suppliers</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var project in Model)
        {
            <tr>
                <td>@project.Name</td>
                <td>@project.CurrentDebitBalance</td>
                <td>@project.CurrentCreditBalance</td>
                <td>@project.TotalDebitBalance</td>
                <td>@project.TotalCreditBalance</td>
                <td>
                    <a asp-controller="Operations" asp-action="GetOperations" asp-route-UserId="@project.ClientId" asp-route-Type ="Clients" asp-route-ProjectId ="@project.Id" class="btn btn-sm btn-success">
                        <i> Client </i>
                    </a>
                </td>
                <td>
                    <a asp-controller="Contractors" asp-action="GetContractorsOfProject" asp-route-id="@project.Id" class="btn btn-sm btn-success">
                        <i> Contractors </i>
                    </a>
                </td>
                <td>
                    <a asp-controller="Suppliers" asp-action="GetSuppliersOfProject" asp-route-id ="@project.Id" class="btn btn-sm btn-success">
                        <i> Suppliers </i>
                    </a>
                </td>


            </tr>
        }
    </tbody>
</table>


<a asp-action="Index" asp-controller="Home" class="btn btn-primary" style="width:150px">
    back to Home
</a>




@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#searchButton').click(function () {
                var searchTerm = $('#searchTerm').val();
                $.ajax({
                    url: '@Url.Action("Search", "Projects")',
                    type: 'GET',
                    data: { Name: searchTerm },
                    success: function (data) {
                        document.getElementById("results").innerHTML = data;
                    },
                });
            });
        });
        $('#clear').click(function () {
            document.getElementById("results").innerHTML = "";
            $('#searchTerm').val("")
        });
    </script>
}